id: P006656
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:13:22.628718
source_metadata:
  id: bdr:W1KG9593
  title: རྟ་མགྲིན་པདྨ་ཡང་གསང་ཁྲོས་པའི་ཆོས་སྐོར།
  author: ''
  volumes:
    f1db61052715461f8c86191079602771:
      image_group_id: I1KG9639
      title: ''
      volume_number: 1
      total_pages: 642
      base_file: v001.txt
    b49a41c15c1a4b43849c32bfc77eb71e:
      image_group_id: I1KG9640
      title: ''
      volume_number: 2
      total_pages: 558
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
